### ISSUE TITLE
Script kills itself after long run

### ISSUE THREAD

**Issue by kristofmiller-idemia** [CrowdStrike/cloud-resource-estimator#48]
Our commercial organization master has over 300 child accounts.
Running the script with the custom role that can jump accounts (we do not have the default one available for use) results in a very long runtime, ending prematurely with a kill message.

E.g.
`main: line 61:   345 Killed                  python3 "${file}" "${args[@]}"`

This produces no output. The alternative is to log in to hundreds of accounts and run this manually, which would take an exorbitant amount of time.

This was run in CloudShell as instructed in the readme and the script appeared to be processing approximately 4 accounts per minute.

**Comment by kristofmiller-idemia** [comment]
Additional issues after running proposed workaround:

Script is hard coded to address commercial account structure. Changing the role reference to "'arn:aws-us-gov:iam::whatever" on line 102 and the region name value to "us-gov-west-1" on line 109 fixes this.

However, one of the OUs throws the following error:

Traceback (most recent call last):
  File "/home/cloudshell-user/cloud-resource-estimator/AWS/aws_cspm_benchmark.py", line 233, in <module>
    for aws in AWSOrgAccess().accounts(args.target_ou):
  File "/home/cloudshell-user/cloud-resource-estimator/AWS/aws_cspm_benchmark.py", line 65, in accounts
    response = client.list_accounts(ParentId=target_ou, NextToken=next_token)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 980, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 1047, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/usr/local/lib/python3.9/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "ParentId", must be one of: NextToken, MaxResults
